name: pytest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
        - windows-latest
        - macos-14    
        python-ver:
        - 3.11
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-ver }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-ver }}
        
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      
    - name: Install python packages
      run: uv sync

    - name: Build Cython code
      run:  pushd src/cis_decoder/; uv run python setup.py build_ext --inplace; popd;
    
    - name: Ruff linting
      run: uv run ruff check src/

    - name: Test with pytest
      run: uv run pytest